#!/usr/bin/env python3
import os
import sys
import ipfsapi
import tempfile
import urllib.parse

api = ipfsapi.connect('127.0.0.1', 5001)

files = sys.argv[1:]

if not files:
    print('No argument.')

with tempfile.TemporaryDirectory() as dirname:
    for file in files:
        os.symlink(os.path.abspath(file), os.path.join(dirname, os.path.basename(file)))
    res_list = api.add(dirname)

dir_res = res_list[-1]
for res in res_list:
    name = res['Name'].rsplit('/', 1)[-1]
    name = urllib.parse.quote(name)
    with_filename = 'https://ipfs.io/ipfs/{}/{}'.format(dir_res['Hash'], name)
    without_filename = 'https://ipfs.io/ipfs/{}'.format(res['Hash'])
    print('{} {}'.format(without_filename, with_filename))
